# Generated by Django 6.0.3 on 2026-04-18 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_relatedvehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatedvehicle',
            name='related',
        ),
        migrations.AddField(
            model_name='relatedvehicle',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatedvehicle',
            name='vehicle_img',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_image/'),
        ),
        migrations.AddField(
            model_name='relatedvehicle',
            name='vehicle_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.vehicle_type'),
            preserve_default=False,
        ),
    ]
