# Generated by Django 6.0.3 on 2026-04-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_remove_relatedvehicle_related_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatedvehicle',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='relatedvehicle',
            name='vehicle_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
