# Generated by Django 6.0.3 on 2026-04-20 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_remove_relatedvehicle_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedvehicle',
            name='main_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_cycles', to='adminapp.vehicle'),
        ),
    ]
