# Generated by Django 6.0.3 on 2026-04-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_relatedvehicle_main_vehicle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelatedVehicle',
        ),
    ]
