# Generated by Django 6.0.3 on 2026-04-27 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentallocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='e.g. 23.022505', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='rentallocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='e.g. 72.571362', max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='CycleTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance'), ('charging', 'Charging')], default='available', max_length=20)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('battery_level', models.IntegerField(default=100, help_text='Battery % (0-100)')),
                ('current_location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='adminapp.vehicle')),
            ],
            options={
                'verbose_name': 'Cycle Tracking',
                'verbose_name_plural': 'Cycle Trackings',
            },
        ),
    ]
