# Generated by Django 6.0.3 on 2026-04-27 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_rentallocation_latitude_rentallocation_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_image',
        ),
    ]
