# Generated by Django 6.0.3 on 2026-04-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('change_of_plans', 'Change of Plans'), ('wrong_booking', 'Booked by Mistake'), ('driver_not_assigned', 'Driver Not Assigned'), ('long_wait', 'Wait Time Too Long'), ('emergency', 'Personal Emergency'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancel_reason_other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('None', 'None'), ('Pending', 'Pending'), ('Processed', 'Processed')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=255),
        ),
    ]
