# Generated by Django 6.0.3 on 2026-04-22 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_booking_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ride',
        ),
    ]
