# Generated by Django 6.0.2 on 2026-04-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0008_delete_ride"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[("Unpaid", "Unpaid"), ("Paid", "Paid")],
                default="Unpaid",
                max_length=20,
            ),
        ),
    ]
