# Generated by Django 6.0.3 on 2026-04-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='aadhaar_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/aadhaar/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_kyc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='other_document_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/other/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pan_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/pan/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
