# Generated by Django 6.0.3 on 2026-04-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_customuser_aadhaar_image_customuser_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
