# Generated by Django 6.0.3 on 2026-04-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_customuser_registration_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='registration_ip',
        ),
    ]
