# Generated by Django 6.0.3 on 2026-04-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_remove_customuser_registration_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
