"""
Django settings for citycycle_project project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

import os
from pathlib import Path


# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# ENVIRONMENT VARIABLES (.env)
# ============================================================
# Secrets such as the map tile API key live in a .env file next to
# manage.py (it is git-ignored). See .env.example.

try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / ".env")
except ImportError:  # python-dotenv not installed -> use real env vars only
    pass


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = "django-insecure-local-citycycle-key-change-this-if-needed"

DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
]


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [
    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Project apps
    "app_modules.userapp",
    "app_modules.adminapp",

    # Third-party
    "rest_framework",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# URL CONFIGURATION
# ============================================================

ROOT_URLCONF = "citycycle_project.urls"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [
            BASE_DIR / "templates",
        ],

        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "citycycle_project.context_processors.map_config",
            ],
        },
    },
]


# ============================================================
# MAPS - LEAFLET + MAPTILER TILES
# ============================================================
# The public OpenStreetMap tile servers block applications that do not
# follow their tile usage policy, so tiles come from MapTiler instead.
# Get a free key at https://cloud.maptiler.com/account/keys/ and put it in .env:
#     MAPTILER_API_KEY=your_key_here
# In the MapTiler dashboard, restrict the key to your allowed HTTP origins
# (e.g. http://127.0.0.1:8000, http://localhost:8000, your production domain).

MAPTILER_API_KEY = os.environ.get("MAPTILER_API_KEY", "").strip()

# Any MapTiler map id, e.g. streets-v2, basic-v2, bright-v2, outdoor-v2
MAPTILER_STYLE = os.environ.get("MAPTILER_STYLE", "streets-v2").strip() or "streets-v2"


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = "citycycle_project.wsgi.application"


# ============================================================
# DATABASE - LOCAL SQLITE
# ============================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"


# ============================================================
# MEDIA FILES - LOCAL STORAGE
# ============================================================

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


# ============================================================
# STORAGE - LOCAL FILESYSTEM
# ============================================================

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },

    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}


# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ============================================================
# CUSTOM USER MODEL
# ============================================================

AUTH_USER_MODEL = "userapp.CustomUser"